### ISSUE TITLE
Wrong time convertion

### ISSUE THREAD

**Issue by dmrsmglov** [schibsted/jslt#107]
Hi, I found an converting error while doing experiment on your playground.

This expression:
```
format-time(parse-time("2021-03-12", "YYYY-MM-DD"), "YYYY-MM-DD")
```
will be evaluate to:
```
"2021-12-362"
```
Probably, you can suggest any workaround to do it correctly or say where I'm wrong
Thanks.
Damir

**Comment by larsga** [comment]
The problem is that `DD` means "day in year". That is, the number of days since January 1.

So `parse-time("2021-03-12", "YYYY-MM-DD")` is actually impossible. It can't both be the 12th day of the year _and_ the month of march.

The `YYYY` is also an issue, because this is the "week year". I'm not sure what that means, but changing to `yyyy` (which is "year") makes it work.

```
format-time(parse-time("2021-03-12", "yyyy-MM-dd"), "yyyy-MM-dd") => "2021-03-12"
```

**Comment by dmrsmglov** [comment]
Thank you for the quick answer
Yes, it absolutely solves my problem :)
