### ISSUE TITLE
Variable Re-assignment

### ISSUE THREAD

**Issue by balagueri21** [schibsted/jslt#223]
If I declare a variable and assign an initial value, can I re-assign a different value to it afterwards?

The code below isn't working:
```
let var = "test"
$var = "test2"

{
  "variable": $var
}
```

Error: `com.schibsted.spt.data.jslt.JsltException: Parse error: Encountered " "=" "= "" at line 2, column 6.`

**Comment by larsga** [comment]
By design this isn't possible. The language is 100% functional in the sense that variables, once created, are not ... variable.

**Comment by balagueri21** [comment]
thanks for clarifying @larsga

**Comment by larsga** [comment]
You're welcome. If you have problems we can probably help with that, too.

**Comment by Psycokwet** [comment]
Hello ! Since my issue is directly affected by the unability to re-assign "non variables" haha, I thought it may be relevant to ask here, in place of @balagueri21 

If we have a case, where we have 
````jslt
let side_calc = {}

def getValues()
  [for (.arr)
    side_calc = $side_calc + .member_or_array_item
    {.another_member_of_array_item}
  ]

{
  array_child1 : getValues(),
  array_child2 : $side_calc 
}
````
with a simple json 
````json
{ "arr" : 
  [
    {"member_or_array_item": {...}, "another_member_of_array_item" : {...}},
    {"member_or_array_item": {...}, "another_member_of_array_item" : {...}},
    ...
  ]
}
````

What do you recon we should do for this type of case? Like, as an elegant use of jslt, because right now, the only alternative I see is duplicating for loops to pass the same area twice, to get the two differents results

Thank you for your work ! Have a nice day !

**Comment by larsga** [comment]
Traversing the array twice is the way to go. 

I would write this as:

```
{
  "array_child1" : [for (.arr) {.another_member_of_array_item}],
  "array_child2" : sum([for(.arr) .member_or_array_item]) // assuming I guessed the type right
}
```

Defining a function in this case I think just bloats the code and makes it harder to read because of the indirection.

**Comment by Psycokwet** [comment]
Hello ! Yes that what I was thinking then. I was wondering if I could only do only one for loop because I have to do a lot of operations really in this loop, so, wanted to use it for multiple thing while I was at it. But, I guess it's just because I come from imperative programming that I think that way, I'm not really used to functionnal languages. And, If I do understand correctly, jslt is based on a functional logic, is it right ?

**Comment by larsga** [comment]
Yes, JSLT is a functional language. That gives implementations much more freedom, and makes it easier to implement optimizations.

If these loops end up being a performance problem please come back, and we can look at how to deal with that.

**Comment by Psycokwet** [comment]
I don't think it will become an issue, but thank you, I will keep that in mind, and try to adapt to functionnal logic. Thank you :)
