### ISSUE TITLE
Pipe Operator not affecting Context

### ISSUE THREAD

**Issue by ronMilne** [schibsted/jslt#266]
Given input Json
```
{
  "director": {
    "name": "Director",
    "individualDirector": {
      "name": "IndividualDirector"
    },
    "otherDirector": {
      "name": "other"
    }
  }
}
```
running this jslt results in "name" outputting "Director", I would have expected the result to be "IndividualDirector"?

```
{
  "director": .director |
  {
    if(.individualDirector) .individualDirector |
    "name": .name
  }
}
```
Ron.

**Comment by larsga** [comment]
The reason is that this part:

`if(.individualDirector) .individualDirector | "name": .name`

is parsed in a different way from what you expect.

`"name" : .name` is not an expression, so what you've actually written is:

```
(
  if(.individualDirector) .individualDirector | "name"
) : .name
```

So the pipe does not affect the `.name`, which is then evaluated in the context of the `"director"` object, giving the actual result. The `pipe` simply changes the context for the "evaluation" of the literal `"name"`.

I hope that explains.

**Comment by larsga** [comment]
Can we close this?

**Comment by ronMilne** [comment]
Sorted thanks for the explanation, makes sense.
