### ISSUE TITLE
Got wrong translate result when pass ObjectNode instead of JsonNode to JSLT.

### ISSUE THREAD

**Issue by ca7erina** [schibsted/jslt#48]
I have an Input:
``` {"A":1,"B":2,"C":{"c1":"asf","c2":12}}```

Rule:
```
def applyX(obj)
{
  "c1" : [$obj.c1, $obj.c1],
  "c2" : [$obj.c2, $obj.c2]
}
{
   "A":"new",
   "data":applyX(.C)
}
```
It works well at http://spt-data-dev-public-web.s3-website-eu-west-1.amazonaws.com/jstl2.html and get correct result.
```
{
  "A" : "new",
  "data" : {
    "c1" : [ "asf", "asf" ],
    "c2" : [ 12, 12 ]
  }
}
```

But in my java code it produced wrong result. Because I didn't convert ObjectNode to JsonNode.
```
Input:
{"A":1,"B":2,"C":{"c1":"asf","c2":12}}
Output:
{"A":"new","data":{"c1":[null,null],"c2":[null,null]}}
```
In my java code, I have the same input and rule.
```
import static com.fasterxml.jackson.databind.SerializationFeature.WRITE_DATES_AS_TIMESTAMPS;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.schibsted.spt.data.jslt.Expression;
import com.schibsted.spt.data.jslt.Parser;

import java.util.HashMap;
import java.util.Map;

public class JsltTester {

  public static void main(String[] args) {
    final String rule =
        "def applyX(obj)\n"
            + "{\n"
            + "  \"c1\" : [$obj.c1, $obj.c1],\n"
            + "  \"c2\" : [$obj.c2, $obj.c2]\n"
            + "}\n"
            + "{\n"
            + "   \"A\":\"new\",\n"
            + "   \"data\":applyX(.C)\n"
            + "}";
    final JsonNode inputJson = createInput();
    final Expression jslt = Parser.compileString(rule);
    final JsonNode output = jslt.apply(inputJson);

    System.out.println("Input:");
    System.out.println(inputJson);
    System.out.println("Output:");
    System.out.println(output);
  }

  private static JsonNode createInput() {
    final ObjectMapper MAPPER =
        new ObjectMapper().disable(WRITE_DATES_AS_TIMESTAMPS).registerModule(new JavaTimeModule());
    final ObjectNode result = MAPPER.createObjectNode();
    result.put("A", 1);
    result.put("B", 2);
    result.put("C", 3);
    Map<String, Object> cMap = new HashMap<>();
    cMap.put("c1", "asf");
    cMap.put("c2", 12);
    result.putPOJO("C", MAPPER.valueToTree(cMap));
    // ---------- code produce the wrong translate result. ---------- 
    return result;
    //----------- uncomment this return statement, will produce correct result. but why have to convert to jsonNode ?---------- 
    //        try {
    //          return MAPPER.readTree(result.toString());
    //        } catch (IOException e) {
    //          throw new RuntimeException(
    //            "An error occurred when create input json." );
    //        }
  }
}
```

**Comment by larsga** [comment]
The problem here is the  `putPOJO` call.

If you call `result.get("C")` you get a node of `com.fasterxml.jackson.databind.node.POJONode`. Calling `C..get("c1")` should return `12`, but it doesn't. You get `null`. So for some reason this kind of node does not behave like normal nodes. I'll look into what's unusual about these nodes.

**Comment by larsga** [comment]
It turns out that `POJONode` is not the same as `ObjectNode`. It represents a single value (like a string or number) that is a wrapped Java object. So you can't actually access the contents of it in any meaningful way. Serializing it works, but you can't treat it as normal JSON. If you want to use it via the API (like JSLT does) you have to do `getPojo`, which returns `Object`, and that isn't something JSLT is going to work with.

However, it turns out to be easy to fix. If you change the `result.putPOJO` line to:
 
```
    result.put("C", tree);
```

then the proper `ObjectNode` that was created by `MAPPER.valuteToTree` gets inserted and everything works. Calling `putPOJO` inserts an opaque wrapper around the data that hides it.

So this isn't actually a JSLT but, just misuse of the Jackson API. :-)
