### ISSUE TITLE
Adding JSLT extension functions

### ISSUE THREAD

**Issue by kalbmj** [schibsted/jslt#52]
Hello,

We are looking to extend the jslt functions with custom java functions, as shown here: https://github.com/schibsted/jslt/blob/master/extensions.md, the one piece that is escaping me is what the def and .jslt file should look like as it calls this function for one of the fields.  Could anyone be so kind as to add that to the example? Thanks in advance.

**Comment by kalbmj** [comment]
Follow up question: Is it possible to extend jslt to support custom java functions, while still using the maven artifact in our project? Thanks in advance.

**Comment by larsga** [comment]
If you implement a JSLT function in Java you can pass it to the `Parser` object. That will make it available in the JSLT environment. There's no need for any `def` statement, because the Java code provides the function implementation. Calling the function will be like calling any other JSLT function.

And, yes, you can depend on the Maven artifact and supply a JSLT function from your own code. Schibsted does that in our own systems.

I hope this clears things up.

**Comment by kalbmj** [comment]
Great, thank you very much for the clarification.
