### ISSUE TITLE
JSLT Transform issue.

### ISSUE THREAD

**Issue by rjagirdar** [schibsted/jslt#58]
Hi, 
I am currently trying to create an empty json array and simply trying to add elements, It seems to be able to add only one element. When trying to add the second element it throws an error.

`def addToList(list, obj) 
  $list + [$obj]

def event(name, value, desc)
  {
    "name" : $name,
    "value" : $value,
    "description" : $desc
  }

def parse(object)
  let events = []
  addToList($events, event("switch", "on", "TurnedOn"))
  addToList($events, event("mode", "prewash", "Mode Changed to"))

parse(.)`

**Comment by larsga** [comment]
Yes, JSLT is a functional language, not an imperative language. So you can't write a transform in the

```statement1;
statement2;
statement3;
...
```

style, because the syntax just doesn't support that. JSLT consists of expressions that evaluate to JSON, not statements.

Also, there is no concept of modifying anything. So your `addToList` returns a new list every time.

You can do this, if you rewrite the `parse` function to:

```
def parse(object)
  addToList(
    addToList([], event("switch", "on", "TurnedOn")),
    event("mode", "prewash", "Mode Changed to")
  )
```

However, this is a strange way to use the language. It's much easier to simply write the list you want, in the same style that you used with the `event` function:

```
def parse(object)
  [
    event("switch", "on", "TurnedOn"),
    event("mode", "prewash", "Mode Changed to")
  ]
```

This is also far easier to read.

**Comment by larsga** [comment]
I see you've opened a new issue after getting an answer to this one. Are you satisfied with the answer? If I don't hear anything I will just close this issue.
