### ISSUE TITLE
Add strict validation mode to throw exception when dot expression resolves to null

### ISSUE THREAD

**Issue by rudolfv** [schibsted/jslt#64]
Currently JSLT is quite forgiving where if the evaluation of a dot expression resolves to null, the transformation still passes.

In some cases this is desirable, but for my use case, stricter validation is required and an exception should be thrown if this is encountered. I would suggest two modes of operation, one which is the current approach and another which I would label the "strict validation/transformation" mode.

I did a very quick scan of the codebase and it seems like this is the point from where the expression should be thrown:
https://github.com/schibsted/jslt/blob/master/src/main/java/com/schibsted/spt/data/jslt/impl/DotExpression.java#L48

The mode flag should either be added during parsing of the JSLT and construction of the Expression or when the apply method is invoked, still haven't made up my mind which one would be best. I guess providing it on the apply method would be more flexible.

Another option would be to add it to the language grammar to make it more explicit.

**Comment by larsga** [comment]
> Currently JSLT is quite forgiving where if the evaluation of a dot expression resolves to null, 
> the transformation still passes.

Would you really want the transform to fail if _any_ dot expression at all, anywhere in the transform, gives null? That sounds rather extreme. 

Can you explain this use case in more detail?

**Comment by larsga** [comment]
Thinking more about this, I can't imagine you actually want this, because then you can't have optional values anywhere. Every single value everywhere has to always be present, or the transform will fail. It has to be very rare that this is the case.

What you can do is something like this:

```
def require(value)
  if ($value)
    $value
  else
    error("Missing value!") // you might want to include a string parameter to provide more info

{
  "foo" : require(.bar.foo),
  "bar" : require(foo.bar),
  // ...
}
```

Another solution is to (in your transform) make a list of all the required fields, and then actually verify that they are present in the output, and complain if they are not. That is, you can write something like:

```
def require(object, fields)
  let tmp = [for ($fields) if (not(contains(., $object))) error("Field " + . + " missing!")]
  $object

require({
  "foo" : require(.bar.foo),
  "bar" : require(foo.bar),
  // ...
}, ["foo", "bar", ...]
)
```

Or you can validate the output of the transform with a JSON Schema, or ... There are many possibilities.

**Comment by rudolfv** [comment]
@larsga You are completely right, the above options provide more than enough flexibility for what I want to achieve without having to add anything to JSLT. I am closing this.
