### ISSUE TITLE
Access a parent node

### ISSUE THREAD

**Issue by thorstenhilker** [schibsted/jslt#79]
Hi!

I wonder, if it is possible to access the parent node from a nested node? 
With a variable it would work. But maybe there is a more elegant way. 

Regards,
Thorsten

**Comment by larsga** [comment]
Jackson, which JSLT is built on, doesn't support that. And there would be a performance cost to it, because it would mean that every time a value is inserted in an array or object it has to be copied (its parent has changed). So I have tried to avoid supporting it.

As you say, in practice you can often get around it by using a variable. I recommend that.

**Comment by thorstenhilker** [comment]
Thank you again for your quick answer!

Regards,
Thorsten
